version: "3.8"

networks:
  default:
    driver: bridge

volumes:
  node_modules:
  postgres:

services:
  postgres:
    image: postgres:10.8-alpine
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build: server
    container_name: br-server
    working_dir: /usr/src/app
    command: yarn dev
    depends_on:
      - postgres
    expose:
      - 3000
      - 9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
